= Gefüllte Mürbteigkekse mit weißer Canache

== Zutaten

.Mürbteig
* 30 dkg glattes Mehl
* 1 Ei
* 1 Pkg Vanillezucker
* 1 Prise Salz
* 10 dkg Staubzucker
* 10 dkg geriebene Mandeln
* 20 dkg weiche Butter

.Canache
* 100 g flüssiges Schlagobers
* 150 g weiße Kuvertüre

.Garnitur
* 50 g geschmolzene weiße Kuvertüre

== Zubereitung

1. Zutaten der Reihe nach in eine Rührschüssel geben und mit dem Handmixer (Knethaken) alles glatt verrühren.

2. Für ca. 3 Stunden kalt stellen.

3. Den Teig kurz noch einmal zusammenkneten, auf leicht bemehlter Arbeitsfläche ca. 3mm dick ausrollen. Mit gezacktem Ausstecher (ca. 5 cm Durchmesser) ausschneiden.

4. Auf mittlerer Schiene bei 180° ca. 14 Minuten backen.

5. Fur die Canache Schlagobers aufkochen, fein gehackte Kuvertüre hinzufügen und so lange rühren, bis eine homogene Masse entsteht. Auskühlen lassen.

6. Kurz aufrühren, in einen Dressiersack füllen und auf einen Teil der Mürbteigkekse dressieren, anderen Teil aufsetzen und kurz trocknen lassen.

7. Zum Garnieren die 50 g weiße Kuvertüre schmelzen, mit einem Löffel über die Kekse Linien ziehen.

