= Kulach/Cinnamon Rolls

Makes:: 9-inch pie pan's worth +3

== Ingredients

=== Dough

* 1 pkg yeast (7g dry/18g fresh)
* 1/4c (50g) sugar
* 1c milk
* 1 tsp salt
* 1 egg 
* 3 1/2 - 3 3/4c flour
* 1/4c (57g) butter
* 1/2 tsp lemond rind (opt.)

=== Cinnamon Sugar Filling

* butter
* 1/2c (100g) sugar
* 1 1/2 tbsp cinnamon

== Instructions

* Scald milk and butter, add salt, let cool.

* Mix yeast and sugar. Slowly mix in milk mixture.

* Scramble egg and mix in - for multiple eggs, add in one at a time.

* Add flour cup-wise, switch to kneading once too stiff to mix. Cover with 1 tsp oil, let rise 1h.

* Push down, let rise another hour.

=== Cinnamon Rolls

* Shape into rectangle, add butter + cinnamon-sugar mix, leaving 1cm on edge to roll. Cut into inch-thick slices, put into oiled pan. Let rise until doubled. Bake at 220°C for 15 min.

==== Overnight Cinnamon Rolls
* After putting into pan, cover tightly with aluminum foil. Put in fridge overnight (8-12h).

* Let rise 2h, then bake as instructed.

=== Kulache

==== Nut Filling

* Crush nuts with rolling pin.

* Mix in egg white, sugar, lemon zest.

* Add nuts until desired texture is achieved (should be on the dry side), taste and adjust if needed.

* Mix in raisins if using.

==== Cheese Filling

* If using cottage cheese, dry and strain, then add minute tapioca to absorb excess moisture. Otherwise, ricotta might be an alternative.

* Mix in egg yolk, sugar, lemon zest or vanilla to taste.

* Add raisins if using. Alternatively, try cherries.

==== Assembly

* Shape into rectangle, cut into 3 inch squares. Put ~1 tsp of filling in center, then fold as desired.

* Let rise on baking sheet until doubled, about 1h, then bake at 220°C for 15 min.
