= Lasagne

Ergibt:: 1 Blech
Zubereitung:: 40 Minuten
Backzeit:: 45 Minuten

== Zutaten

* Lasagneblätter
* 300g Cottage Cheese
* 300g Mascarpone
* 1 Ei
* 1 Zwiebel
* (1 Karotte)
* 600ml Tomatenmark
* etwas Tomatenmark aus der Tube (gesalzen)
* 1 Würfel Gemüsesuppe
* 600g Faschiertes (gemischt)
* 4 Zehen Knoblauch
* Mozzarella
* Oregano
* Salz, Pfeffer
* Olivenöl
* (1 Zucchini)

== Zubereitung
1. Für die weiße Sauce in einer Schüssel Cottage Cheese und Mascarpone vermischen.
Mit Oregano, Salz und Pfeffer würzen; das Ei unterrühren.

2. Falls gewünscht, Zucchini in Scheiben schneiden.

3. Für die rote Sauce Zwiebel (optional mit Karotten) in einer großen Pfanne in Olivenöl anschwitzen.
Faschiertes hinzufügen und durchrösten. Tomatenmark dazugeben, mit Salz, Pfeffer, Oregano, gepresstem
Knoblauch und Gemüsesuppenwürfel würzen. Bei mittlerer Temperatur schwach köcheln lassen, bis das
Fleisch die Aromen der Gewürze aufgenommen hat.

4. Backrohr laut Verpackung der Lasagneblätter vorheizen (meist 200°C)

4. Eine große Backform mit Lasagneblättern auslegen, mit einem Teil der roten Sauce bestreichen.
Sofern Zucchini verwendet werden, Zucchinischeiben darauf legen und mit Salz und Pfeffer bestreuen.
Weiße Sauce darauf geben, und Lasagneblätter darauf. So fortfahren; die letzte Schicht Lasagneblätter
nur mit roter Sauce bestreichen. Mozzarella darüber geben und mit Oregano bestreuen.

5. Backform mit Alufolie bedecken und abdichten, auf mittlerer Schiene 30 Minuten backen lassen.
Nach 30 Minuten herausnehmen, Alufolie entfernen und weitere 15 Minuten backen. Backzeit eventuell
nach Anleitung der Lasagneblätter anpassen.
