= Rotes Linsen-Curry

== Zutaten

* 300g rote Linsen
* 1L Wasser
* 3 EL Öl oder Butterschmalz
* 1 TL Kreuzkümmel, grob gemörselt oder gehackt
* 1 Zwiebel, fein gehackt
* 3 EL Kokosraspeln
* 500g Tomaten, geschält und gewürfelt
** auch Dosentomaten
* 1 TL Kurkuma
* 2 TL Salz
* 50mL Schlagobers
* 1-2 TL Garam Masala

== Zubereitung

1. Die roten Linsen unter fließendem Wasser waschen, bis das Waschwasser klar bleibt.
Danach in 1L Wasser bei mittlerer Hitze aufkochen und bei geöffnetem Topf (Vorsicht - kocht schnell über!) auf kleiner Flamme köcheln lassen, bis die Linsen weich sind.
Die Linsen samt dem Kochwasser beiseite stellen.

2. In einem großem Topf das Fett erhitzen, feingehackte Zwiebel goldgelb braten,
dann die Kreuzkümmel mitbraten und schließliche die Kokosraspeln zugeben und ca.
1 min. weiterbraten - Vorsicht, die Kokosraspeln brennen leicht an!

3. Die Tomaten hinzufügen, bei geschlossenem Deckel etwa 5 min. auf kleiner
Flamme köcheln lassen.

4. Kurkuma, Salz und Linsen mitsamt Kochflüssigkeit hinzufügen und alles ca.
10-15 min. lang auf kleiner Flamme köcheln lassen.

5. Schlagobers zugießen und mit Garam Masala würzen. Chili oder Pfeffer je nach
Geschmack dazugeben. 
