= Mac and Cheese with Roasted Broccoli

adapted from: https://www.epicurious.com/recipes/food/views/macaroni-and-cheese-recipe 

== Ingredients 

=== Roast Broccoli 

* 1 head broccoli 
* 3 cloves garlic 
* olive oil 
* salt, pepper to taste 

=== Macaroni and Cheese 

==== Panko Topping 

* 2 Tbsp unsalted butter 
* 2 Tbsp EVOO 
* 2 cups panko 
* 2 large garlic cloves, finely chopped 
* 60g grated parmesan (abt. 1/2 cup) 
* 1/4+1/8 tsp salt 
* dried oregano and basil, to taste 

=== Mac and Cheese 

* 1 tsp salt 
* 300g macaroni noodles 
* 113g butter 
* 6 Tbsp all-purpose flour 
* 946mL milk 
* 177mL heavy cream 
* 1/2 tsp white pepper 
* 454g coarsely grated cheddar 
* 60g grated parmesan 

== Preparation 

=== Broccoli 

1. Cut broccoli into bite-sized pieces, on small size. Use stem if decent - peel (thick skin) and cut into half-coins. 
Crush garlic and tear into smaller pieces. 

2. Mix all ingredients in 13x9" pan, and roast at 180°C for ~15 minutes, mixing every 5 minutes - should be just tender. 
Take out, and set aside to make mac - mac will be added to same pan. 

=== Topping 

1. Melt butter over med heat, add EVOO, stirring until foam subsides. 

2. Add panko and garlic. Cook, stirring, until golden brown, about 4-6 minutes. 

3. Transfer crumbs to bowl, add all other ingredients and mix thoroughly. 

=== Mac and cheese 

1. Cook noodles until just al dente, set aside. 

2. Preheat oven to 205°C. 

3. In a big pot, melt butter over medium-low heat. Sprinkle flour over butter, whisk to incorporate. 
Stir constantly with wooden spoon until roux is light golden, about 4 minutes. 

4. Gradually pour in milk and heavy cream, whisking constantly. 
Raise heat to medium-high and bring to a low boil, whisking constantly. 
Reduce to a simmer, whisking occasionally, until sauce is thick and coats the back of a spoon, about 3 minutes. 

5. Mix in salt and pepper. 
Add cheese in three batches, mixing each time to incorporate and melt fully before next batch is added. 
Remove from heat. 

6. Mix mac, sauce and broccoli, transfer to baking dish (or just mix in that). 
Place on baking sheet. 
Sprinkle topping over mac and bake until golden and bubbling, 18-22 minutes. 
