= Pecan Pumpkin Pie 

adapted from: https://www.bonappetit.com/recipe/pecan-rye-pumpkin-pie 

edited mainly for formatting 

== Ingredients 

* dough for single-crust pie 

=== Pumpkin Filling

* 4 eggs, one separated 
* 1 15-oz. can Libby’s 100% Pure Pumpkin
* ¾ cup heavy cream 
* ¼ cup granulated sugar
* 2 Tbsp. rye whiskey
* 1 tsp. ground cinnamon
* small piece fresh ginger, minced
* ¼ tsp. freshly grated nutmeg
* ¼ tsp. ground cardamom
* Small pinch of ground cloves
* 6 Tbsp. light brown sugar
* 2 Tbsp. unsalted butter, melted 
* 1/2 tsp. salt

=== Pecan Topping 

* 1½ cups whole pecans 
* 2 Tbsp. light brown sugar 
* 3/4 tsp salt 
* 1 Tbsp. butter, melted 
* 1 Tbsp. pure maple syrup 

== Assembly 

=== Crust 

1. Mix according to recipe. Chill dough 30 min. 

2. Roll dough out and shape crust, prick bottom and sides well. Chill 30 min. 

3. Preheat oven to 230°C. 

4. Separate egg - use the white for the crust, the yolk for the filling. 

5. Brush pie with egg white, then bake for 10-12 min. until golden. 

6. Once ready for filling, set oven to 175°C. 

=== Filling 

1. Mix filling ingredients together, blend with immersion blender until smooth and homogenous; try not to aerate. 

2. Pour into crust and bake at 175°F until mostly set, with slight wobble in center when gently shaken, 40-45 min. 

3. While pie is baking, prepare the pecan topping. 

=== Pecan Topping 

1. Just before pie is done, toast pecans on rimmed baking sheet until slightly darkened and fragrant, 8-10 min. 

2. Whisk remaining egg white with brown sugar and salt until foamy, about 30 sec. Add syrup and butter, whisk just to combine. Add pecans and toss to coat. 

3. Once pie has reached consistency described above, top with pecans, allowing excess egg white mixture to drip back into bowl. 

4. Return pie to oven, bake until filling is completely set - knife or tester inserted into center should come out completely clean - and nuts are not tacky to the touch, 8-10 min. 

5. Let cool 2h. Serve with whipped cream. 
