= Ricotta-Speck-Ravioli

Ergibt:: 2-3 Portionen
Zubereitung:: 2 Stunden
Kochzeit:: 5 Minuten

== Zutaten

* 200g Ricotta
* 100g Parmesan
* 30g Speck
* Pfeffer und Salz zum Abschmecken.

=== Für den Nudelteig

* 30dag Mehl
* 1 Ei
* 1/8L Wasser

== Zubereitung

1. Zutaten für den Nudelteig vermischen.
Nur salzen, wenn er am selben Tag verwendet wird.

2. In einer Schüssel Ricotta und Parmesan gut vermischen.

3. Speck in einer Pfanne braten, zerkleinern und unter die Ricotta-Parmesan-Mischung mengen.
Füllmischung mit Pfeffer und Salz abschmecken.

4. Jeweils ca. ein Viertel des Teiges möglichst rechteckig auswalken.
Falls notwendig zurecht schneiden.

5. Mit zwei Teelöffeln Füllung portionieren und auf einer Hälfte des Teiges setzen.
Teigränder mit Wasser bestreichen, dann Teig in der Mitte zusammenfalten.
Dabei möglichst die Luft entweichen lassen.
In Ravioli schneiden.

6. In einer grossen Pfanne Wasser zum kochen bringen, salzen, Hitze reduzieren und die Ravioli ca. 5 Minuten sieden lassen.
