= Schokoladetaler

Ergibt:: 40 Stück (2 Backbleche)
Zubereitungszeit:: ca. 1h 30 min. (zum Auskühlen ca. 1h)

== Zutaten

=== Mürbteig

* 100g glattes Mehl
* 60g Butter
* 40g Staubzucker
* 1 Pkg. Vanillezucker
* Schale von 1 kl. Zitrone (unbehandelt)
* 2 Dotter

=== Fülle

* 100g weiße Schokolade
* 40g Butter
* 40g Staubzucker
* 4 EL Orangensaft
* Schale von 1 kl. Zitrone (unbehandelt)

=== Garnitur

 * 50g Bitterschokolade

== Zubereitung

1. Mehl und 1 Prise Salz mischen, sieben, mit Butter verbröseln und mit
 Staubzucker, Vanillezucker, abgeriebener Zitronenschale und Dottern rasch zu
 einem glatten Teig kneten. Den Teig in Frischhaltefolie wickeln und ca. 30 min.
 kaltstellen.

2. Backrohr auf 200°C vorheizen. Backblech mit Backpapier belegen.
 Teig auf einer leicht bemehlten Arbeitsfläche messerrückendick ausrollen.
 80 Scheiben (Ø ca. 4 cm) ausstechen und auf die Kekse legen.
 Kekse im vorgeheizten Rohr ca. 10 min. backen, herausnehmen und auskühlen lassen.

3. Für die Fülle Schokolade schmelzen. Butter, Zucker, Orangensaft und
 abgeriebener Zitronenschale cremig rühren, die Schokolade untermischen.

4. 40 Kekse dünn mit Schokoladencreme bestreichen, restliche Kekse draufsetzen.

5. Für die Garnitur Schokolade über Wasserdampf schmelzen und die Kekse damit
 verzieren. 
