= Shrimp Scampi with Tomatoes 

Adapted from:: https://bevcooks.com/2019/03/shrimp-scampi-with-tomatoes-and-crusty-bread/#mpprecipe-container 
Serves:: 1

== Ingredients 

* 150g shrimp 
** as large as possible; peeled, deveined, thawed 
** heads, shells can (theoretically) be used to make shrimp butter for extra shrimp flavor 
* 3 Tbsp. butter 
* 1 Tbs. olive oil 
* 3 cloves garlic, minced 
* 1/4 cup white wine 
* 3/4 cup cherry/snack tomatoes 
** make or break the dish - make when tomatoes are in-season 
* red pepper flakes 
* 1/4 lemon 
* salt 
* parsley 

== Instructions 

* If using shrimp shells, make shrimp butter lite - fry the shells in a saucepan with 2 Tbs. butter. Strain butter and set aside. 
** If making legit shrimp butter, it needs to be made at least an hour before. 
* Melt 1 Tbsp. butter and the olive oil in a pan over medium high heat. Add garlic, tomatoes and sauté for 30 seconds, until fraggrant. Add remaining (shrimp) butter, wine, crushed red pepper. Let simmer until the tomatoes begin to wilt. 
* Add shrimp to pan, season with good pinch of salt. Add half the lemon to the pan, let shrimp cook until opaque (wait until pink a bit over halfway through, flip, cook until done). Stir in parsley and, if needed, season with more salt and lemon to taste. 
* Serve with baguette and white wine. 


= Shrimp butter (legit)  

Source:: fish cooking course 

== Ingredients 

* 200-250g shrimp shells and heads 
* 250g butter 
* 1/16l water/stock (veg or fish) 

== Instructions 

* Roast shells in very little oil until red and strongly fragrant. 
* Add butter and water/stock, let simmer 10 minutes. 
* Roughly blend, let cool at least 1h or overnight. 
* Reheat and strain. 
* Use in above recipe as-is, or add salt and lemon to taste. 
