= Taler Maripan-Kekse

Ergibt:: 30 Stück (1 Backblech)
Zubereitungszeit:: ca. 1h 15 min. (ca. 1h Auskülen)

== Zutaten

* 200g glattes Mehl
* 2 TL Backpulver
* 140g Butter
* 80g Staubzucker
* 1 Pkg. Vanillezucker
* 1 Dotter
* 40g Mandeln (gerieben)

=== Belag

* 200g Rohmarzipan
* 50g Staubzucker
* 1 EL Kirschwasser
* 100g Marillenmarmelade
* 100g Kochschokolade
* 30 Mandelhälften (geschält)

== Zubereitung

1. Mehl mit Backpulver versieben, mit Butter verbröseln,
und mit Staubzucker, Vanillezucker, Dotter und Mandeln rasch zu einem glatten Teig kneten.
Teig in Frischhaltefolie wickeln und ca. 1/2 Stunde kaltstellen.

2. Backrohr auf 175°C vorheizen, Backblech mit Backpapier belegen.
Teig auf einer leicht bemehlten Arbeitsfläche messerrückendick ausrollen.
Scheiben (Ø ca. 4 cm) ausstechen, auf das Blech legen und im vorgeheizten Rohr
(mittlere Schiene) goldgelb backen. Kekse herausnehmen und auskühlen lassen.

3. Marzipan mit Zucker und Kirschwasser verkneten und auf einer mit Staubzucker
bestreuten Arbeitsfläche messerrückendick ausrollen. Aus der Masse 30 Scheiben
(Ø ca. 4 cm) ausstechen.

4. Ausgekühlte Kekse dünn mit Marmelade bestreichen, Maripanscheiben drauflegen
und behutsam andrücken.

5. Schokolade schmelzen lassen, langsam 1 EL Butter einrühren.
Kekse zur Hälfte in Schokolade tauchen, auf ein Kuchengitter setzen und mit
Mandelhälften belegen. Schokolade festwerden lassen.
