---
source: Torten, Kuchen, Schnitten
category: sweets
kind: christmas-cookies
---

= Bittermandelschnitten

== Zutaten

.Masse
* 30 dkg glattes Mehl
* 20 dkg Butter
* 10 dkg Staubzucker
* Schale von 1/2 Zitrone
* 1 Ei

.Belag
* 10 dkg Butter
* 10 dkg Staubzucker
* 2 Eier
* 15 dkg Walnüsse (gerieben)
* 1 Röhrchen Bittermandel-Aroma
* Marillenmarmelade

== Zubereitung
Mehl und 1 Prise Salz mischen, sieben, mit Butter verbröseln und mit Zucker, abgeriebener Zitronenschale und Ei rasch zu einem glatten Teig kneten. Den Teig in Frischhaltefolie wickeln und da. 1/2 Stunde kaltstellen.

Backrohr auf 180° vorheizen. Backpapier in der Größe des Backbleches zuschneiden und mit wenig Mehl stauben. Teig auf dem Papier ca. 1/2 cm dick ausrollen, auf das Blech legen und im vorgeheizten Rohr (mittlere Schiene) ca. 10 Minuten backen.

Inzwischen warme Butter mit Zucker cremig rühren, Eier nach und nach einrühren. Nüsse und Bittermandelaroma untermischen.

Teig aus dem Rohr nehmen, mit Marillenmarmelade und Nussmasse bestreichen und (mittlere Schiene) fertigbacken (dauert ca. 15 Minuten). Masse aus dem Rohr nehmen, auskühlen lassen und in Rauten schneiden. Besonders appetitlich sehen die Kekse aus, wenn man sie zur Hälfte in geschmolzene Schokolade tunkt.
