---
source: Torten, Kuchen, Schnitten
category: sweets
kind: cake
---

= Donauwellen

== Zutaten

.Masse
* 150 g weiche Butter
* 150 g Zucker
* 1 Pkg Vanillezucker
* 4 Eier
* 200 g Mehl
* 3 TL Backpulver
* 2 EL Kakaopulver
* 1 EL Milch

.Creme
* 1/2 Pkg Vanillepuddingpulver zum Kochen
* 1/4 l Milch
* 3 EL Zucker
* 125 g weiche Butter

.Sonstiges
* 1 kleines Glas entsteinte Weichseln (Schattenmorellen; etwa 185 g Abtropfgewicht)
* 1 Pkg Kuchenglasur (100 g)

== Zubereitung
Eine 24 cm große Springform gründlich fetten. Den Backofen auf 175° vorheizen.

Die Weichseln in einem Sieb gut abtropfen lassen.

Die Butter mit dem Zucker und dem Vanillezucker cremig rühren. Nacheinander die Eier dazugeben und den Teig hell-schaumig aufschlagen. Das Mehl und das Backpulver vermischen, unter den Teig rühren.

Die Hälfte des Teiges in der vorbereiteten Springform glattstreichen. Den restlichen Teig mit dem Kakaopulver und der Milch verrühren. Mit einem Teigschaber über den hellen Teig streichen. Die Kirschen darauf verteilen.

Den Kuchen auf der mittleren Schiene im Ofen etwa 45 Minuten backen. In der Form auskühlen lassen.

Inzwischen für die Creme den Pudding nach der Packungsbeschreibung mit Milch und Zucker kochen. Abkühlen lassen. Die weiche Butter cremig rühren, löffelweise den abgekühlten Pudding unterrühren. Über dem Kuchen glattstreichen.

Die Kuchenglasur nach der Packungsbeschreibung schmelzen lassen, den Kuchen damit überziehen. Den Guss fest werden lassen.
