---
source: Torten, Kuchen, Schnitten
category: sweets
kind: pastry
---

= Faschingskrapfen 2

== Zutaten
* 28 dkg glattes Mehl
* Prise Salz
* 175 ml Milch
* 5 Dotter (zimmerwarm)
* 7 dkg Butter
* 1 1/2 EL Rum
* geriebene Zitronenschale
* 1 TL Vanillezucker
* 2 dkg Germ

== Zubereitung
Mehl und Salz in eine Schüssel geben und warm stellen.

Milch lippenwarm erwärmen, in 3 Schalen gießen. In die Erste sprudelt man die Dotter, den Rum und die Zitronenschale. In die Zweite Zucker und Germ. In die Dritte die zerlassene Butter.

Ins warme Mehl eine Mulde machen, nach und nach die Milchmischungen dazugeben. Den Teig abschlagen, bis er sich von der Schüssel löst.

Auf einem bemehlten Brett fingerdick auswalken. Auf der Hälfte mit einem Ausstecher Kreise nur markieren. Marmelade in die Mitte häufen. Die gleiche Anzahl Kreise ausstechen, über die Marmelade legen. Die Ränder andrücken. Mit einem etwas kleineren Ausstecher bekommen die Krapfen ihre endgültige Form.

erst jetzt die Krapfen zugedeckt aufblähen lassen. In reichlich Rapsöl (180°) 3 Minuten zugedeckt, nach dem Umdrehen 3 Minuten offen fertig backen.
