---
source: Mehlspeisen
category: sweets
kind: pastry
---

= Faschingskrapfen

== Zutaten
* 1/2 kg Mehl
* 4 dkg Germ
* 4 dkg Rama
* 6 dkg Staubzucker
* 4 Dotter
* 1/4 l Milch
* Prise Salz
* 1 EL Rum
* 1 Pkg Vanillezucker
* Zitronenschale
* Marmelade zum Füllen
* Öl zum Backen

== Zubereitung
Die Germ fein zerbröseln und mit versiebtem Mehl vermischen.
Der Teig wird nun so lange abgeschlagen, bis er sich von Geschirr und Löffel löst und Blasen wirft.
Der Teig darf keinesfalls zu fest sein, etwas Milch dazu.
Zudecken und an einem warmen Ort aufgehen lassen.

Nach dem Rasten den Teig auf ein bemehltes Brett gleichmäßig ca. 1 cm dick ausrollen.
Auf einer Hälfte des Teiges mit rundem Ausstecher Kreise anzeichnen, in die Mitte feste Marillenmarmelade geben.
Aus der 2. Teighälfte werden nun ebengroße Scheiben ausgestochen, mit der bemehlten Seite nach oben auf die Kreise gelegt, die Ränder mit den Fingerspitzen leicht angedrückt und mit einem kleineren Ausstecher aufs Neue ausgestochen.
Die Krapfen mit der Unterseite nach oben auf ein bemehltes Tuch legen, zugedeckt aufgehen lassen.

Die Krapfen werden in schwimmendem, nicht zu heißem Öl mit der Oberseite nach unten zugedeckt auf einer Seite herausgebacken. Bei Erreichen von hellbrauner Farbe das Geschirr aufdecken und auf der zweiten Seite ebenfalls zu goldbrauner Farbe fertigbacken.

Aus dem Öl heben und nach dem Abtropfen anzuckern.
