---
source: Lose Zettel
category: sweets
kind: christmas-cookies
---

= Fruchtige Knopfkekse

== Zutaten
* 150 g Butter
* 50 g Marzipan-Rohmasse
* 80 g Zucker
* 1 Prise Salz
* 1 Dotter
* 200 g Mehl
* 120 g gemahlene Mandeln ohne Haut
* 150 g Holunder-Zwetschgen-Marmelade
* bunte Zuckerdekoration (Tube)

== Zubereitung
Butter in kleine Stücke schneiden, Marzipan raspeln. Butter, Zucker, Salz, Dotter und Marzipan mit den Knethaken des Handrührgeräts verkneten. Mehl und Mandeln zugeben und mit den Händen schnell zu einem glatten Teig verkneten. Mürbteig flach formen, in Folie wickeln und ca. 1 Stunde kühlen.

Teig ca. 4 mm dick auswalken, mit zwei runden Ausstechern (3 und 4 cm Durchmesser) je 20 Kreise ausstechen. Bei der Hälfte der Kreise mit einer Lochtülle (Durchmesser 8 mm) zwei oder vier Knopflöcher ausstechen. Im vorgeheizten Backrohr bei 175° 8 bis 10 Minuten goldbraun backen und gut auskühlen lassen.

Marmelade durch ein Sieb streichen. Die Rückseite der Kekse ohne Löcher mit Marmelade bestreichen. Darauf je ein Keks mit Löchern setzen und leicht andrücken. Mit bunter Zuckerschrift verzieren (Fäden) und über Nacht trocknen lassen.
