---
source: Weihnachtsbäckereien
category: sweets
kind: christmas-cookies
---

= Himbeersternchen

== Zutaten

.Masse
* 37 dkg glattes Mehl
* 1/4 kg Butter
* 1/8 kg Staubzucker
* 1 Dotter
* Schale von 1/2 Zitrone

.Fülle
* 10 dkg Himbeermarmelade

.Glasur
* 6 EL Himbeergeist
* 1 TL Zitronensaft
* 1/4 kg Staubzucker (fein gesiebt)

== Zubereitung
Mehl mit 1 Prise Salz mischen, sieben, mit Butter verbröseln und mit Zucker, Dotter und abgeriebener Zitronenschale rasch zu einem glatten Teig kneten. Den Teig in Frischhaltefolie wickeln und ca. 1/2 Stunde kaltstellen.

Backrohr auf 180° vorheizen. Backbleche mit Backpapier belegen. Teig auf einer leicht bemehlten Arbeitsfläche messerrückendick ausrollen. 90 Sterne (Durchmesser ca. 4 cm) ausstechen und auf die Bleche legen. Im vorgeheizten Rohr (mittlere Schiene) ca. 10 Minuten backen. Kekse aus dem Rohr nehmen und auskühlen lassen.

Die Hälfte der Kekse dünn mit Marmelade bestreichen, die restlichen Kekse daraufsetzen und die Oberfläche ebenfalls mit Marmelade bestreichen. Kekse auf ein Kuchengitter legen.

Für die Glasur Himbeergeist, Zitronensaft und Zucker gut verrühren. Kekse gleichmäßig mit Glasur bestreichen und trocknen lassen.
