---
source: Lose Zettel
category: sweets
kind: christmas-cookies
---

= Holländer Teegebäck (Schwarz-Weiß-Gebäck)

== Zutaten
* 30 dkg Butter
* 15 dkg Staubzucker
* 1 Prise Salz
* 40 dkg Mehl
* 3 dkg Kakaopulver

== Zubereitung
Die Butter auf einem Backbrett mit dem Staubzucker und dem Salz geschmeidig verarbeiten. Dann das gesiebte Mehl darunterwirken, den Teig teilen und unter eine Hälfte das gesiebte Kakaopulver unterarbeiten. Die beiden Teige kühl stellen.

Nach Lust und Laune Gebäcke formen, z.B.: Hellen und dunklen Mürbteig gleich stark (ca. 1 cm) ausrollen, davon Stangen schneiden und diese dann mit Eiweiß jeweils zu einem Schachbrett zusammenkleben. Hellen Mürbteig dünn ausrollen und damit dann dieses Schachbrett einschlagen.

Oder: beide Teige dünn ausrollen, übereinanderlegen und dann zusammen aufrollen. So entsteht eine Spirale.

Jedenfalls Teigstücke jeweils mit dem Pinsel dünn mit Eiweiß bestreichen, damit sie gut zusammenkleben und beim Backen nicht auseinanderfallen.

Die Teigstangen in 1/2 cm starke Scheiben schneiden, auf ein nicht gefettetes Backblech legen und bei 180° bis 190° hell backen.
