= Malakofftorte

== Zutaten

Diese Zutatenliste ist für die 1.5-fache Masse des Originalrezepts. Für die Originalliste siehe unten.

.Buttercreme
* 22 dkg Butter (sehr weich)
* 15 dkg Zucker
* 4 TL Rum
* 2 Pkg. Vanillezucker
* 2 Dotter
* 1 Ei
* 1/16 l kalte Milch (erfahrungsgemäß reicht etwas weniger)

.Torte
* 400 g Biskotten
* Rum zum Tunken (38%)
* 250 ml Schlagobers
* 1 EL Staubzucker
* Schokoraspeln zum Dekorieren
* Rum-Kokos-Kugeln zum Dekorieren

== Zubereitung

Für die Buttercreme Butter mit Zucker, Dottern und Ei schaumig rühren, Rum löffelweise dazu rühren. Kalte Milch *tropfenweise* einmengen, bis die Creme relativ weich ist. Creme kaltstellen.

Rum mit Wasser verdünnen, Springform mit Backpapier auslegen. Biskotten jeweils rasch in Rum wenden und eng aneinandergereiht in Springform einschlichten. Die Biskotten sollten bis ganz zum Rand liegen. Wenn notwendig, Biskotten dafür auch brechen.

Über jede Schicht Biskotten Buttercreme auftragen, die die Zwischenräume auffüllt und die Biskotten dünn abdeckt. Dann Form 90° drehen und mit der nächsten Schicht wie zuvor fortfahren. Dabei entstehen ca. 4-5 Schichten.

Torte 1-2 Stunden kalt stellen, bis die Creme fest ist. Torte stürzen.

Schlagobers schlagen, Staubzucker einrühren; Torte oben und am Rand dünn damit bestreichen. Schlagobersrand zur Zierde mit gezackter Teigkarte rundum einkerben. Mit Spritzsack Oberseite der Torte mit restlichem Schlagobers dekorieren; mittig mit Schokoraspeln bestreuen, außen im Kreis Rum-Kokos aufsetzen.

== Originale Zutatenliste

.Buttercreme
* 15 dkg Butter
* 10 dkg Zucker
* 1 Dotter
* 1 Ei
* 1 Pkg. Vanillezucker
* 3 EL Rum
* 1/16 L kalte Milch
