---
source: Weihnachtsbäckereien
category: sweets
kind: christmas-cookies
---

= Marzipan-Kekse

== Zutaten

.Masse
* 200 g glattes Mehl
* 2 TL Backpulver
* 140 g Butter
* 80 g Staubzucker
* 1 Pkg. Vanillezucker
* 1 Dotter
* 40 g Mandeln (gerieben)

.Belag
* 200 g Rohmarzipan
* 50 g Staubzucker
* 1 EL Kirschwasser
* 100 g Marillenmarmelade
* 100 g Kochschokolade
* 30 Mandelhälften (geschält)

== Zubereitung

Mehl mit Backpulver versieben, mit Butter verbröseln,
und mit Staubzucker, Vanillezucker, Dotter und Mandeln rasch zu einem glatten Teig kneten.
Teig in Frischhaltefolie wickeln und ca. 1/2 Stunde kaltstellen.

Backrohr auf 175° vorheizen, Backblech mit Backpapier belegen.
Teig auf einer leicht bemehlten Arbeitsfläche messerrückendick ausrollen.
Scheiben (Durchmesser ca. 4 cm) ausstechen, auf das Blech legen und im vorgeheizten Rohr
(mittlere Schiene) goldgelb backen. Kekse herausnehmen und auskühlen lassen.

Marzipan mit Zucker und Kirschwasser verkneten und auf einer mit Staubzucker
bestreuten Arbeitsfläche messerrückendick ausrollen. Aus der Masse 30 Scheiben
(Durchmesser ca. 4 cm) ausstechen.

Ausgekühlte Kekse dünn mit Marmelade bestreichen, Marzipanscheiben drauflegen
und behutsam andrücken.

Schokolade schmelzen lassen, langsam 1 EL Butter einrühren.
Kekse zur Hälfte in Schokolade tauchen, auf ein Kuchengitter setzen und mit
Mandelhälften belegen. Schokolade fest werden lassen.
