---
source: Torten, Kuchen, Schnitten
category: sweets
kind: christmas-cookies
---

= Mohnkipferln

== Zutaten

.Masse
* 1/4 kg glattes mehl
* 20 dkg kalte Butter
* 10 dkg Mohn (gerieben)
* 7 1/2 dkg Staubzucker
* 1 Dotter
* Salz

.Vanillezucker
* 1 Pkg Vanillezucker
* Staubzucker
* 1/2 TL Zimt

== Zubereitung
Mehl und 1 Prise Salz mischen, sieben, mit Margarine verbröseln und mit Mohn, Staubzucker und Dotter rasch zu einem glatten Teig kneten. Sollte der Teig zu fest sein, ein paar Tropfen kalte Milch untermischen. Teig in Frischhaltefolie wickeln und ca. 1 Stunde kaltstellen.

Backrohr auf 160° vorheizen. Backbleche mit Backpapier belegen. Aus dem Teig auf einer leicht bemehlten Arbeitsfläche zwei Rollen formen, ca. 1 dkg schwere Stücke abschneiden, zu Kipferln formen und auf die Bleche legen.

Kipferln im vorgeheizten Rohr (mittlere Schiene) ca. 12 Minuten backen. Kipferln aus dem Rohr nehmen. Staubzucker mit Vanillezucker mischen, in ein Sieb geben und die noch heißen Kipferln damit bestreuen.
