---
source: Mehlspeisen
category: sweets
kind: cake
---

= Mozartkuppel

== Zutaten

.Masse
* 5 Eier
* 14 dkg Feinkristallzucker
* 1 Pkg Vanillezucker
* 16 dkg Mehl
* 5 dkg Rama
* Zitronenschale

.Fülle
* 1/4 l Schlagobers
* 5 dkg Staubzucker
* 1/4 kg Weichselfleisch (Kompott)
* Weichselsaft
* Rum

.Parisercreme
* 1/4 l Schlagobers
* 1/4 kg Kochschokolade

.Dekor
* Marzipanrose
* kandierte Früchte

== Zubereitung
Die ganzen Eier, Zucker, Zitronenschale erst warm (im Wasserbad), dann kalt aufschlagen. Fett (zerlassen) einschlagen. Dann mit gesiebtem Mehl vermengen.

In eine befettete Kuppelform füllen. Bei ca. 150°-170° langsam 1 1/4 Stunden backen.

Nach dem Erkalten in 5 Scheiben schneiden, die man mit Rum und Weichselsaft tränkt. Mit geschlagenem, gesüßten Obers, unter das man das geschnittene Weichselfleisch mengt, werden die Scheiben zur Kuppelform zusammengesetzt.

Für die Parisercreme Schlagobers aufkochen lassen, von der Kochstelle nehmen, und die Schokolade bis zum völligen Auflösen einrühren. Erkalten lassen und zum Gebrauch zu gewünschter Konsistenz aufrühren. Kuppel mit Parisercreme bestreichen.

Mit kandierten Früchten und einer Marzipanrose verzieren.
