---
source: Torten, Kuchen, Schnitten
category: sweets
kind: cake
---

= Patzerlgugelhupf

== Zutaten

.Masse
* 1/2 kg Mehl
* 10 dkg Butter
* 10 dkg Zucker
* 1/2 Pkg Vanillezucker
* 2 Dotter
* 3 dkg Germ
* 3/16 l Milch
* Zitronenschale

.Topfenfülle
* 10 dkg Topfen
* 1 TL Zucker
* 1 Dotter
* Rosinen
* Zitronenschale

.Mohnfülle
* 10 dkg Mohn
* 1 EL Honig
* 1 EL Zucker
* Zimt
* Zitronenschale

.Nussfülle
* 10 dkg Nüsse
* 1 TL Zucker
* 1 TL Brösel
* 1/8 l heiße Milch
* Prise Zimt
* Rum

.Powidlfülle
* 10 dkg Powidl
* etwas Rum

== Zubereitung
Dampfl zubereiten: Milch etwas erwärmen, 1 EL Zucker und 4 EL Mehl darin verrühren, Germ hineinbröseln und ebenfalls verrühren. Mit Geschirrtuch abdecken und ca. 1/2 Stunde gehen lassen.

Zimmerwarme Butter mit dem Mehl vermengen, nach und nach Dampfl und restliche Zutaten für die Masse hinzufügen. Verkneten, bis ein homogener Teig entsteht.

Teig zu einer Kugel formen, in eine Schüssel geben, mit Geschirrtuch bedecken und 1/2 Stunde gehen lassen. Danach nochmals durchkneten, und wieder 1/2 Stunde gehen lassen. Je öfter dieser Vorgang wiederholt wird, desto flaumiger wird der Teig.

Füllungen zubereiten: Für die Topfenfülle alle Zutaten gut verrühren. Für die Powidlfülle Rum mit Powidl verrühren.

Für die Mohnfülle etwas Milch (ca. 1/8 l) erwärmen, Honig und Zucker darin verrühren. Mohn hinzufügen und quellen lassen. Mit Zimt und Zitronenschale verfeinern.

Für die Nussfülle Milch erwärmen, Rum hinzufügen und Zucker darin auflösen. Nach und nach über die Nüsse und Brösel gießen und diese verrühren. Die Masse sollte nicht zu flüssig werden. Mit Zimt verfeinern.

Einen Teil des Teiges auf einer bemehlten Arbeitsfläche auswalken, mit Teigrad Rechtecke ausschneiden. Jedes Rechteck mit einer der Füllungen füllen, zu einem Patzerl formen und in eine bemehlte Gugelhupfform platzieren. Dabei idealerweise auf eine abwechslungsreiche Schichtung achten.

In der Form noch einmal etwas gehen lassen, ins kalte Rohr geben und bei leicht geöffneter Türe auf 170° aufheizen lassen. Sobald das Rohr die 170° erreicht hat, Türe schließen und ca. Stunde lang backen.

_Anweisungen für die Zubereitung von Christoph_
