---
source: Mehlspeisen
category: sweets
kind: pastry
---

= Schnecken

== Zutaten

.Masse
* 25 dkg Mehl
* 2 dkg Germ
* 1/10 l lauwarme Milch
* 3 dkg Zucker 6 dkg Butter
* 1 Ei
* 1/2 KL Salz

.Fülle
* 3 dkg Butter
* 2 EL Zucker
* 1 KL Zimt
* 5 dkg geriebene Nüsse oder Mandeln
* 5 dkg gehackte Rosinen

.Glasur
* 20 dkg Zucker
* 2 EL Zitronensaft
* 1 KL Rum

== Zubereitung
Die Germ mit Prise Zucker in Milch gehen lassen.
Das Mehl mit der gegangenen Germ, mit Zucker, Butter und dem Ei zu einem festen Teig verarbeiten, schlagen bis er Blasen wirft.
1 Stunde an einem warmen Ort gehen lassen.

Den gegangenen Teig fingerdick ausrollen, mit der zerlassenen Butter bepinseln, mit Zimt-Zucker-Gemisch und den gehackten Nüssen bestreuen und zu einem festen Strudel formen. Diesen in daumenbreite Stücke schneiden, mit der Schnittfläche auf ein gefettetes Blech legen, zudecken, um die Hälfte aufgehen lassen. Bei mittelhoher Hitze hellbraun backen.

Für die Glasur den Zucker mit Zitronensaft zu einer dicken Masse verrühren, diese erwärmen und den Rum zusetzen.
Die noch warmen Schnecken mit Glasur bestreichen.
