---
source: Torten, Kuchen, Schnitten
category: sweets
kind: cake
annotation: sehr gutes Rezept
---

= Schokoladetorte

== Zutaten

.Masse
* 14 dkg Butter
* 12 dkg Staubzucker
* Dotter und Klar von 6 Eiern
* 13 dkg Kochschokolade
* 13 dkg griffiges Mehl
* 11 dkg Kristallzucker
* 15 dkg Ribiselmarmelade
* Butter zum Ausstreichen
* Mehl zum Ausstäuben

.Glasur
* 15 dkg Kochschokolade
* 7 1/2 dkg Butter

== Zubereitung
Handwarme Butter und Staubzucker schaumig rühren, nach und nach Eidotter einrühren. Schokolade im Backrohr schmelzen, in den Abtrieb einmengen.

Eiklar mit Kristallzucker zu steifem Schnee schlagen. Mehl mit Schnee abwechselnd in den Abtrieb einmengen.

In gebutterte, bemehlte Tortenform füllen und im Backrohr bei 180° ca. 1 Stunde backen.

Torte erkalten lassen, aus der Form lösen, einmal durchschneiden. Mit Ribiselmarmelade dünn füllen, zusammensetzen und auch seitlich und oben mit Marmelade bestreichen.

Kochschokolade und Butter erwärmen, über die Torte gießen und kühl stellen. Nicht verstreichen dann bleibt die Glasur glänzend.
