---
source: Weihnachtsbäckereien
category: sweets
kind: christmas-cookies
---

= Schokoladesterne

== Zutaten
* 25 dkg Mehl
* 1 Messerspitze Salz
* 1 Pkg Vanillezucker
* 1 Ei
* 1 Messerspitze Ingwer
* 15 dkg Butter
* etwas Himbeermarmelade
* 1 Becher Schokoladenglasur (oder erweichte Kochschokolade)
* Walnüsse zum Garnieren

== Zubereitung
Das Mehl auf ein Backblech sieben, in der Mitte eine Vertiefung drücken und Salz, Vanillezucker, Ei und Ingwer hineingeben. Die Butter in Flöckchen auf dem Mehl verteilen und mit einem bemehlten Messer gut mischen. Zu einem glatten Teig kneten und im Kühlschrank zugedeckt 1 Stunde rasten lassen.

Den Teig dann auf dem Backbrett ca. 1/2 cm stark ausrollen und Sterne ausstechen. Auf ein ungefettetes Backblech legen und bei 180° ca. 10 bis 15 Minuten hellgelb backen.

Die Hälfte der Sterne auf der Unterseite mit der erhitzten Himbeermarmelade bestreichen und die übrigen Sterne daraufsetzen. Die Schokoladeglasur auflösen, die Gebäcke eintauchen, und solange die Glasur noch warm ist, mit je einer Walnusshälfte belegen.
