---
source: Weihnachtsbäckereien
category: sweets
kind: christmas-cookies
---

= Sesam-Fruchtbusserln

== Zutaten
* 55 runde Vollwert-Oblaten (klein)
* 10 dkg Marillen (getrocknet)
* 5 dkg Zitronat
* 8 dkg Rosinen
* 10 dkg Mandelblättchen
* 8 dkg Sesam
* 5 dkg Butter
* 1/8 l Schlagobers
* 4 EL Honig
* 4 EL Weizen-Vollmehl
* Zimt
* Nelkenpulver
* Vanille-Aroma

== Zubereitung
Rosinen in kleine Stücke schneiden. Marillen und Zitronat kleinwürfelig schneiden. Butter erhitzen, mandeln und Sesam zugeben, ca. 2 Minuten anschwitzen und dabei öfter umrühren. Obers zugießen, Honig einrühren und die Masse aufkochen. Hitze reduzieren.

Früchte, Mehl sowie ein wenig Zimt, Nelkenpulver und Vanille-Aroma zugeben und unter ständigem Rühren ziehen lassen, bis die Masse festzuwerden beginnt.

Backrohr auf 180° vorheizen, Backbleche mit Backpapier belegen. Oblaten auf die Bleche legen, die Fruchtmasse mit einem Löffel in kleinen Häufchen daraufsetzen. Kekse im vorgeheizten Rohr (mittlere Schiene) 15 bis 20 Minuten backen.
