---
source: Weihnachtsbäckerei
category: sweets
kind: christmas-cookies
---

= Zimtblätter

== Zutaten
* 50 dkg glattes Mehl
* 25 dkg Butter
* 25 dkg Staubzucker
* 1 TL Vanillezucker
* 1 TL Zimt
* 1 Prise Salz
* geriebene Zitronenschale
* 2 Eier
* 2 Dotter
* 25 dkg geriebene Haselnüsse
* Schokoladeglasur

== Zubereitung
Mehl, Butter und Staubzucker mit den restlichen Zutaten rasch zu einem glatten Teig kneten. Den Teig in Folie wickeln und 30 Minuten im Kühlschrank rasten lassen.

Backrohr auf 200° vorheizen. Teig auf einer bemehlten Arbeitsfläche ca. 5 mm dick ausrollen. Mit einem glatten Ausstecher Scheiben (Durchmesser ca. 6 cm) ausstechen. Anschließend mit demselben Ausstecher jeweils links und rechts blattförmige Stücke abstechen. Mit einem kleinen Messer die Blattstruktur auf die Oberfläche der Kekse ritzen.

Kekse auf die befetteten und bemehlten Backbleche legen und so lange backen, bis die Ränder hellbraun sind (ca. 10 bis 12 Minuten).

Kekse aus dem Backrohr nehmen und auskühlen lassen. Die Kekse zur Hälfte in Schokoladeglasur tauchen, ein wenig abstreifen, auf Backpapier legen und die Glasur fest werden lassen.
